#!/usr/bin/env python3
"""
Visual Direction asset pipeline for Haren's Ether.

  python3 tools/visuals.py add PATH [PATH ...] --project ID --type photo|video|direction
                           [--title "..."] [--meta "..."] [--size tall|wide]
  python3 tools/visuals.py build        # regenerate assets/js/visual-assets.js
  python3 tools/visuals.py list         # show what's in the manifest

PATH can be files or folders. Photos become web-sized WebP (full + thumbnail,
EXIF/GPS stripped). Videos become H.264 MP4 (1080p max, web-streamable) with a
poster frame. Everything is recorded in visual/manifest.json; the site reads the
generated assets/js/visual-assets.js.

Needs: Pillow (pip install pillow) and ffmpeg for video.
"""
import argparse, json, os, re, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "visual" / "manifest.json"
PROJECTS = ROOT / "visual" / "projects.json"
OUT_JS = ROOT / "assets" / "js" / "visual-assets.js"
PHOTO_EXT = {".jpg", ".jpeg", ".png", ".webp", ".tif", ".tiff", ".heic", ".heif"}
VIDEO_EXT = {".mp4", ".mov", ".m4v", ".webm", ".mkv", ".avi"}
FULL_PX, THUMB_PX = 2400, 900


def slug(s):
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower()
    return s or "frame"


def load():
    return json.loads(MANIFEST.read_text()) if MANIFEST.exists() else []


def save(items):
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(items, indent=2, ensure_ascii=False) + "\n")
    build(items)


def build(items=None):
    items = load() if items is None else items
    shown = [i for i in items if i.get("src")]
    projects = json.loads(PROJECTS.read_text()) if PROJECTS.exists() else []
    known = {p["id"] for p in projects}
    for i in shown:
        if i.get("project") not in known:
            print(f"  ! '{i['title']}' has no project (or an unknown one) — it won't appear. Set \"project\" in the manifest.")
    js = ("/* Generated by tools/visuals.py from visual/projects.json + visual/manifest.json — edit those, then run build. */\n"
          "window.VISUAL_PROJECTS = " + json.dumps(projects, indent=2, ensure_ascii=False) + ";\n"
          "window.VISUAL_ASSETS = " + json.dumps(shown, indent=2, ensure_ascii=False) + ";\n")
    OUT_JS.write_text(js)
    print(f"built {OUT_JS.relative_to(ROOT)} · {len(projects)} projects · {len(shown)} frames")


def unique(path):
    p, n = Path(path), 2
    while p.exists():
        p = Path(path).with_name(f"{Path(path).stem}-{n}{Path(path).suffix}")
        n += 1
    return p


def auto_size(w, h):
    if h / w > 1.3:
        return "tall"
    if w / h > 1.9:
        return "wide"
    return ""


def do_photo(src, kind):
    from PIL import Image, ImageOps
    try:
        import pillow_heif; pillow_heif.register_heif_opener()  # optional HEIC support
    except ImportError:
        pass
    im = ImageOps.exif_transpose(Image.open(src)).convert("RGB")
    w, h = im.size
    base = slug(src.stem)
    full = unique(ROOT / "visual" / kind / f"{base}.webp")
    thumb = ROOT / "visual" / kind / "thumbs" / full.name
    thumb.parent.mkdir(parents=True, exist_ok=True)
    for px, dst, q in ((FULL_PX, full, 84), (THUMB_PX, thumb, 80)):
        c = im.copy()
        c.thumbnail((px, px), Image.LANCZOS)
        c.save(dst, "WEBP", quality=q, method=6)  # no EXIF written → location data stripped
    return {"src": rel(full), "thumb": rel(thumb)}, auto_size(w, h)


def do_video(src, kind):
    if not shutil.which("ffmpeg"):
        sys.exit("ffmpeg is needed for video (brew install ffmpeg).")
    base = slug(src.stem)
    out = unique(ROOT / "visual" / kind / f"{base}.mp4")
    poster = ROOT / "visual" / kind / "thumbs" / (out.stem + ".webp")
    poster.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(src),
                    "-vf", "scale='if(gte(iw,ih),min(1920,iw),-2)':'if(gte(iw,ih),-2,min(1920,ih))'", "-c:v", "libx264", "-preset", "slow",
                    "-crf", "24", "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "128k",
                    "-movflags", "+faststart", str(out)], check=True)
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-ss", "1", "-i", str(out),
                    "-frames:v", "1", "-vf", f"scale='min({THUMB_PX},iw)':-2", str(poster)], check=True)
    preview = ROOT / "visual" / kind / "thumbs" / (out.stem + "-preview.mp4")
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(out), "-t", "8", "-an",
                    "-vf", "scale='min(540,iw)':-2", "-c:v", "libx264", "-crf", "30", "-preset", "slow",
                    "-pix_fmt", "yuv420p", "-movflags", "+faststart", str(preview)], check=True)
    probe = subprocess.run(["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries",
                            "stream=width,height", "-of", "csv=p=0", str(out)],
                           capture_output=True, text=True).stdout.strip().split(",")
    w, h = (int(probe[0]), int(probe[1])) if len(probe) == 2 else (16, 9)
    mb = out.stat().st_size / 1e6
    if mb > 95:
        print(f"  ! {out.name} is {mb:.0f} MB — over GitHub's 100 MB limit; trim or host externally.")
    return {"src": rel(out), "poster": rel(poster), "preview": rel(preview)}, auto_size(w, h)


def rel(p):
    return str(Path(p).relative_to(ROOT)).replace(os.sep, "/")


def add(args):
    items = load()
    files = []
    for p in map(Path, args.paths):
        files += sorted(f for f in p.rglob("*") if f.is_file()) if p.is_dir() else [p]
    added = 0
    for f in files:
        ext = f.suffix.lower()
        if ext in PHOTO_EXT:
            media, size = do_photo(f, args.type)
        elif ext in VIDEO_EXT:
            media, size = do_video(f, args.type)
        else:
            continue
        title = args.title or re.sub(r"[-_]+", " ", f.stem).strip().title()
        entry = {"project": args.project, "type": args.type, "title": title,
                 "meta": args.meta or {"photo": "Photography", "video": "Videography",
                                       "direction": "Direction"}[args.type],
                 **media, "size": args.size if args.size is not None else size}
        items.append(entry)
        added += 1
        print(f"  + {entry['src']}  [{entry['size'] or 'standard'}]  {title}")
    save(items)
    print(f"added {added} file(s)")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    a = sub.add_parser("add")
    a.add_argument("paths", nargs="+")
    a.add_argument("--project", required=True, help="project id from visual/projects.json")
    a.add_argument("--type", required=True, choices=["photo", "video", "direction"])
    a.add_argument("--title"); a.add_argument("--meta")
    a.add_argument("--size", choices=["", "tall", "wide"])
    sub.add_parser("build"); sub.add_parser("list")
    args = ap.parse_args()
    if args.cmd == "add":
        add(args)
    elif args.cmd == "build":
        build()
    else:
        for i, it in enumerate(load()):
            print(f"{i:>3}  {it.get('project','?'):<16} {it['type']:<9} {it.get('src') or '(placeholder)':<55} {it['title']}")


if __name__ == "__main__":
    main()
